/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelProductsVariationModel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelProductsVariationModel'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelSalesInvoiceLineModel = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelProductsVariationModel);
  }
}(this, function(ApiClient, DkCloudDataModelProductsVariationModel) {
  'use strict';

  /**
   * The DkCloudDataModelSalesInvoiceLineModel model module.
   * @module model/DkCloudDataModelSalesInvoiceLineModel
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelSalesInvoiceLineModel</code>.
   * @alias module:model/DkCloudDataModelSalesInvoiceLineModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelSalesInvoiceLineModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelSalesInvoiceLineModel} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelSalesInvoiceLineModel} The populated <code>DkCloudDataModelSalesInvoiceLineModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('SequenceNumber'))
        obj.sequenceNumber = ApiClient.convertToType(data['SequenceNumber'], 'Number');
      if (data.hasOwnProperty('ItemCode'))
        obj.itemCode = ApiClient.convertToType(data['ItemCode'], 'String');
      if (data.hasOwnProperty('Text'))
        obj.text = ApiClient.convertToType(data['Text'], 'String');
      if (data.hasOwnProperty('Text2'))
        obj.text2 = ApiClient.convertToType(data['Text2'], 'String');
      if (data.hasOwnProperty('Warehouse'))
        obj.warehouse = ApiClient.convertToType(data['Warehouse'], 'String');
      if (data.hasOwnProperty('Quantity'))
        obj.quantity = ApiClient.convertToType(data['Quantity'], 'Number');
      if (data.hasOwnProperty('UnitQuantity'))
        obj.unitQuantity = ApiClient.convertToType(data['UnitQuantity'], 'Number');
      if (data.hasOwnProperty('UnitCode'))
        obj.unitCode = ApiClient.convertToType(data['UnitCode'], 'String');
      if (data.hasOwnProperty('UnitPrice'))
        obj.unitPrice = ApiClient.convertToType(data['UnitPrice'], 'Number');
      if (data.hasOwnProperty('UnitPriceWithTax'))
        obj.unitPriceWithTax = ApiClient.convertToType(data['UnitPriceWithTax'], 'Number');
      if (data.hasOwnProperty('Discount'))
        obj.discount = ApiClient.convertToType(data['Discount'], 'Number');
      if (data.hasOwnProperty('DiscountAmount'))
        obj.discountAmount = ApiClient.convertToType(data['DiscountAmount'], 'Number');
      if (data.hasOwnProperty('DiscountAmountWithTax'))
        obj.discountAmountWithTax = ApiClient.convertToType(data['DiscountAmountWithTax'], 'Number');
      if (data.hasOwnProperty('TotalAmount'))
        obj.totalAmount = ApiClient.convertToType(data['TotalAmount'], 'Number');
      if (data.hasOwnProperty('TotalAmountWithTax'))
        obj.totalAmountWithTax = ApiClient.convertToType(data['TotalAmountWithTax'], 'Number');
      if (data.hasOwnProperty('Dim1'))
        obj.dim1 = ApiClient.convertToType(data['Dim1'], 'String');
      if (data.hasOwnProperty('Variations'))
        obj.variations = ApiClient.convertToType(data['Variations'], [DkCloudDataModelProductsVariationModel]);
    }
    return obj;
  }

  /**
   * @member {Number} sequenceNumber
   */
  exports.prototype.sequenceNumber = undefined;

  /**
   * @member {String} itemCode
   */
  exports.prototype.itemCode = undefined;

  /**
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * @member {String} text2
   */
  exports.prototype.text2 = undefined;

  /**
   * @member {String} warehouse
   */
  exports.prototype.warehouse = undefined;

  /**
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * @member {Number} unitQuantity
   */
  exports.prototype.unitQuantity = undefined;

  /**
   * @member {String} unitCode
   */
  exports.prototype.unitCode = undefined;

  /**
   * @member {Number} unitPrice
   */
  exports.prototype.unitPrice = undefined;

  /**
   * @member {Number} unitPriceWithTax
   */
  exports.prototype.unitPriceWithTax = undefined;

  /**
   * @member {Number} discount
   */
  exports.prototype.discount = undefined;

  /**
   * @member {Number} discountAmount
   */
  exports.prototype.discountAmount = undefined;

  /**
   * @member {Number} discountAmountWithTax
   */
  exports.prototype.discountAmountWithTax = undefined;

  /**
   * @member {Number} totalAmount
   */
  exports.prototype.totalAmount = undefined;

  /**
   * @member {Number} totalAmountWithTax
   */
  exports.prototype.totalAmountWithTax = undefined;

  /**
   * @member {String} dim1
   */
  exports.prototype.dim1 = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelProductsVariationModel>} variations
   */
  exports.prototype.variations = undefined;


  return exports;
}));
