/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelGeneralContactInfo = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkCloudDataModelGeneralContactInfo model module.
   * @module model/DkCloudDataModelGeneralContactInfo
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelGeneralContactInfo</code>.
   * @alias module:model/DkCloudDataModelGeneralContactInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelGeneralContactInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelGeneralContactInfo} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelGeneralContactInfo} The populated <code>DkCloudDataModelGeneralContactInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Phone'))
        obj.phone = ApiClient.convertToType(data['Phone'], 'String');
      if (data.hasOwnProperty('Direct'))
        obj.direct = ApiClient.convertToType(data['Direct'], 'String');
      if (data.hasOwnProperty('Mobile'))
        obj.mobile = ApiClient.convertToType(data['Mobile'], 'String');
      if (data.hasOwnProperty('Fax'))
        obj.fax = ApiClient.convertToType(data['Fax'], 'String');
      if (data.hasOwnProperty('Telex'))
        obj.telex = ApiClient.convertToType(data['Telex'], 'String');
      if (data.hasOwnProperty('Email'))
        obj.email = ApiClient.convertToType(data['Email'], 'String');
      if (data.hasOwnProperty('URL'))
        obj.URL = ApiClient.convertToType(data['URL'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} phone
   */
  exports.prototype.phone = undefined;

  /**
   * @member {String} direct
   */
  exports.prototype.direct = undefined;

  /**
   * @member {String} mobile
   */
  exports.prototype.mobile = undefined;

  /**
   * @member {String} fax
   */
  exports.prototype.fax = undefined;

  /**
   * @member {String} telex
   */
  exports.prototype.telex = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} URL
   */
  exports.prototype.URL = undefined;


  return exports;
}));
