/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelSettingsDimmensionSetting = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkCloudDataModelSettingsDimmensionSetting model module.
   * @module model/DkCloudDataModelSettingsDimmensionSetting
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelSettingsDimmensionSetting</code>.
   * @alias module:model/DkCloudDataModelSettingsDimmensionSetting
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelSettingsDimmensionSetting</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelSettingsDimmensionSetting} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelSettingsDimmensionSetting} The populated <code>DkCloudDataModelSettingsDimmensionSetting</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Dim1Enabled'))
        obj.dim1Enabled = ApiClient.convertToType(data['Dim1Enabled'], 'Boolean');
      if (data.hasOwnProperty('Dim2Enabled'))
        obj.dim2Enabled = ApiClient.convertToType(data['Dim2Enabled'], 'Boolean');
      if (data.hasOwnProperty('Dim3Enabled'))
        obj.dim3Enabled = ApiClient.convertToType(data['Dim3Enabled'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {Boolean} dim1Enabled
   */
  exports.prototype.dim1Enabled = undefined;

  /**
   * @member {Boolean} dim2Enabled
   */
  exports.prototype.dim2Enabled = undefined;

  /**
   * @member {Boolean} dim3Enabled
   */
  exports.prototype.dim3Enabled = undefined;


  return exports;
}));
