/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelSalesQuoteLine = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkCloudDataModelSalesQuoteLine model module.
   * @module model/DkCloudDataModelSalesQuoteLine
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelSalesQuoteLine</code>.
   * @alias module:model/DkCloudDataModelSalesQuoteLine
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelSalesQuoteLine</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelSalesQuoteLine} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelSalesQuoteLine} The populated <code>DkCloudDataModelSalesQuoteLine</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('SequenceNumber'))
        obj.sequenceNumber = ApiClient.convertToType(data['SequenceNumber'], 'Number');
      if (data.hasOwnProperty('ItemCode'))
        obj.itemCode = ApiClient.convertToType(data['ItemCode'], 'String');
      if (data.hasOwnProperty('Text'))
        obj.text = ApiClient.convertToType(data['Text'], 'String');
      if (data.hasOwnProperty('Text2'))
        obj.text2 = ApiClient.convertToType(data['Text2'], 'String');
      if (data.hasOwnProperty('Warehouse'))
        obj.warehouse = ApiClient.convertToType(data['Warehouse'], 'String');
      if (data.hasOwnProperty('Quantity'))
        obj.quantity = ApiClient.convertToType(data['Quantity'], 'Number');
      if (data.hasOwnProperty('UnitPrice'))
        obj.unitPrice = ApiClient.convertToType(data['UnitPrice'], 'Number');
      if (data.hasOwnProperty('UnitPriceWithTax'))
        obj.unitPriceWithTax = ApiClient.convertToType(data['UnitPriceWithTax'], 'Number');
      if (data.hasOwnProperty('UnitCode'))
        obj.unitCode = ApiClient.convertToType(data['UnitCode'], 'String');
      if (data.hasOwnProperty('Discount'))
        obj.discount = ApiClient.convertToType(data['Discount'], 'Number');
      if (data.hasOwnProperty('DiscountPercent'))
        obj.discountPercent = ApiClient.convertToType(data['DiscountPercent'], 'Number');
      if (data.hasOwnProperty('TotalAmount'))
        obj.totalAmount = ApiClient.convertToType(data['TotalAmount'], 'Number');
      if (data.hasOwnProperty('TotalAmountWithTax'))
        obj.totalAmountWithTax = ApiClient.convertToType(data['TotalAmountWithTax'], 'Number');
      if (data.hasOwnProperty('Reference'))
        obj.reference = ApiClient.convertToType(data['Reference'], 'String');
      if (data.hasOwnProperty('Memo'))
        obj.memo = ApiClient.convertToType(data['Memo'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} sequenceNumber
   */
  exports.prototype.sequenceNumber = undefined;

  /**
   * @member {String} itemCode
   */
  exports.prototype.itemCode = undefined;

  /**
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * @member {String} text2
   */
  exports.prototype.text2 = undefined;

  /**
   * @member {String} warehouse
   */
  exports.prototype.warehouse = undefined;

  /**
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * @member {Number} unitPrice
   */
  exports.prototype.unitPrice = undefined;

  /**
   * @member {Number} unitPriceWithTax
   */
  exports.prototype.unitPriceWithTax = undefined;

  /**
   * @member {String} unitCode
   */
  exports.prototype.unitCode = undefined;

  /**
   * @member {Number} discount
   */
  exports.prototype.discount = undefined;

  /**
   * @member {Number} discountPercent
   */
  exports.prototype.discountPercent = undefined;

  /**
   * @member {Number} totalAmount
   */
  exports.prototype.totalAmount = undefined;

  /**
   * @member {Number} totalAmountWithTax
   */
  exports.prototype.totalAmountWithTax = undefined;

  /**
   * @member {String} reference
   */
  exports.prototype.reference = undefined;

  /**
   * @member {String} memo
   */
  exports.prototype.memo = undefined;


  return exports;
}));
