/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelPermissionProductPermissionModel = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkCloudDataModelPermissionProductPermissionModel model module.
   * @module model/DkCloudDataModelPermissionProductPermissionModel
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelPermissionProductPermissionModel</code>.
   * @alias module:model/DkCloudDataModelPermissionProductPermissionModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelPermissionProductPermissionModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelPermissionProductPermissionModel} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelPermissionProductPermissionModel} The populated <code>DkCloudDataModelPermissionProductPermissionModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Products'))
        obj.products = ApiClient.convertToType(data['Products'], 'String');
      if (data.hasOwnProperty('ProductReport'))
        obj.productReport = ApiClient.convertToType(data['ProductReport'], 'String');
      if (data.hasOwnProperty('Barcodes'))
        obj.barcodes = ApiClient.convertToType(data['Barcodes'], 'String');
      if (data.hasOwnProperty('Warehouses'))
        obj.warehouses = ApiClient.convertToType(data['Warehouses'], 'String');
      if (data.hasOwnProperty('Attachments'))
        obj.attachments = ApiClient.convertToType(data['Attachments'], 'String');
      if (data.hasOwnProperty('ForeignPrice'))
        obj.foreignPrice = ApiClient.convertToType(data['ForeignPrice'], 'String');
      if (data.hasOwnProperty('Units'))
        obj.units = ApiClient.convertToType(data['Units'], 'String');
      if (data.hasOwnProperty('Changes'))
        obj.changes = ApiClient.convertToType(data['Changes'], 'String');
      if (data.hasOwnProperty('Settings'))
        obj.settings = ApiClient.convertToType(data['Settings'], 'String');
      if (data.hasOwnProperty('CostPrices'))
        obj.costPrices = ApiClient.convertToType(data['CostPrices'], 'String');
      if (data.hasOwnProperty('Transactions'))
        obj.transactions = ApiClient.convertToType(data['Transactions'], 'String');
      if (data.hasOwnProperty('HideColumns'))
        obj.hideColumns = ApiClient.convertToType(data['HideColumns'], ['String']);
      if (data.hasOwnProperty('Enabled'))
        obj.enabled = ApiClient.convertToType(data['Enabled'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.ProductsEnum} products
   */
  exports.prototype.products = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.ProductReportEnum} productReport
   */
  exports.prototype.productReport = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.BarcodesEnum} barcodes
   */
  exports.prototype.barcodes = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.WarehousesEnum} warehouses
   */
  exports.prototype.warehouses = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.AttachmentsEnum} attachments
   */
  exports.prototype.attachments = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.ForeignPriceEnum} foreignPrice
   */
  exports.prototype.foreignPrice = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.UnitsEnum} units
   */
  exports.prototype.units = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.ChangesEnum} changes
   */
  exports.prototype.changes = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.SettingsEnum} settings
   */
  exports.prototype.settings = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.CostPricesEnum} costPrices
   */
  exports.prototype.costPrices = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.TransactionsEnum} transactions
   */
  exports.prototype.transactions = undefined;

  /**
   * @member {Array.<String>} hideColumns
   */
  exports.prototype.hideColumns = undefined;

  /**
   * @member {module:model/DkCloudDataModelPermissionProductPermissionModel.EnabledEnum} enabled
   */
  exports.prototype.enabled = undefined;



  /**
   * Allowed values for the <code>products</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProductsEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>productReport</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProductReportEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>barcodes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BarcodesEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>warehouses</code> property.
   * @enum {String}
   * @readonly
   */
  exports.WarehousesEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>attachments</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AttachmentsEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>foreignPrice</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ForeignPriceEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>units</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UnitsEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>changes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ChangesEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>settings</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SettingsEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>costPrices</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CostPricesEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>transactions</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TransactionsEnum = {
    /**
     * value: "Full"
     * @const
     */
    full: "Full",

    /**
     * value: "View"
     * @const
     */
    view: "View",

    /**
     * value: "Modify"
     * @const
     */
    modify: "Modify",

    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "Deny"
     * @const
     */
    deny: "Deny"
  };

  /**
   * Allowed values for the <code>enabled</code> property.
   * @enum {String}
   * @readonly
   */
  exports.EnabledEnum = {
    /**
     * value: "Enabled"
     * @const
     */
    enabled: "Enabled",

    /**
     * value: "Disabled"
     * @const
     */
    disabled: "Disabled",

    /**
     * value: "Blocked"
     * @const
     */
    blocked: "Blocked"
  };
  return exports;
}));
