/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelCustomersCustomerPropertyModel = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkCloudDataModelCustomersCustomerPropertyModel model module.
   * @module model/DkCloudDataModelCustomersCustomerPropertyModel
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelCustomersCustomerPropertyModel</code>.
   * @alias module:model/DkCloudDataModelCustomersCustomerPropertyModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelCustomersCustomerPropertyModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelCustomersCustomerPropertyModel} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelCustomersCustomerPropertyModel} The populated <code>DkCloudDataModelCustomersCustomerPropertyModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('Attribute'))
        obj.attribute = ApiClient.convertToType(data['Attribute'], 'String');
      if (data.hasOwnProperty('Option'))
        obj.option = ApiClient.convertToType(data['Option'], 'String');
      if (data.hasOwnProperty('Comment'))
        obj.comment = ApiClient.convertToType(data['Comment'], 'String');
      if (data.hasOwnProperty('Modified'))
        obj.modified = ApiClient.convertToType(data['Modified'], 'Date');
    }
    return obj;
  }

  /**
   * @member {String} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {String} attribute
   */
  exports.prototype.attribute = undefined;

  /**
   * @member {String} option
   */
  exports.prototype.option = undefined;

  /**
   * @member {String} comment
   */
  exports.prototype.comment = undefined;

  /**
   * @member {Date} modified
   */
  exports.prototype.modified = undefined;


  return exports;
}));
