/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelGeneralAttachmentModel', 'model/DkCloudDataModelGeneralDateRange', 'model/DkCloudDataModelMembersApplicationBankAccount', 'model/DkCloudDataModelMembersApplicationContact', 'model/DkCloudDataModelMembersApplicationDetail', 'model/DkCloudDataModelMembersMaternityLeave', 'model/DkCloudDataModelMembersWorkPlaceHistory'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelGeneralAttachmentModel'), require('./DkCloudDataModelGeneralDateRange'), require('./DkCloudDataModelMembersApplicationBankAccount'), require('./DkCloudDataModelMembersApplicationContact'), require('./DkCloudDataModelMembersApplicationDetail'), require('./DkCloudDataModelMembersMaternityLeave'), require('./DkCloudDataModelMembersWorkPlaceHistory'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelMembersApplication = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelGeneralAttachmentModel, root.DkPlusApi.DkCloudDataModelGeneralDateRange, root.DkPlusApi.DkCloudDataModelMembersApplicationBankAccount, root.DkPlusApi.DkCloudDataModelMembersApplicationContact, root.DkPlusApi.DkCloudDataModelMembersApplicationDetail, root.DkPlusApi.DkCloudDataModelMembersMaternityLeave, root.DkPlusApi.DkCloudDataModelMembersWorkPlaceHistory);
  }
}(this, function(ApiClient, DkCloudDataModelGeneralAttachmentModel, DkCloudDataModelGeneralDateRange, DkCloudDataModelMembersApplicationBankAccount, DkCloudDataModelMembersApplicationContact, DkCloudDataModelMembersApplicationDetail, DkCloudDataModelMembersMaternityLeave, DkCloudDataModelMembersWorkPlaceHistory) {
  'use strict';

  /**
   * The DkCloudDataModelMembersApplication model module.
   * @module model/DkCloudDataModelMembersApplication
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelMembersApplication</code>.
   * @alias module:model/DkCloudDataModelMembersApplication
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelMembersApplication</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelMembersApplication} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelMembersApplication} The populated <code>DkCloudDataModelMembersApplication</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Member'))
        obj.member = ApiClient.convertToType(data['Member'], 'String');
      if (data.hasOwnProperty('BankAccount'))
        obj.bankAccount = DkCloudDataModelMembersApplicationBankAccount.constructFromObject(data['BankAccount']);
      if (data.hasOwnProperty('Contact'))
        obj.contact = DkCloudDataModelMembersApplicationContact.constructFromObject(data['Contact']);
      if (data.hasOwnProperty('Fund'))
        obj.fund = ApiClient.convertToType(data['Fund'], 'String');
      if (data.hasOwnProperty('GrantDescription'))
        obj.grantDescription = ApiClient.convertToType(data['GrantDescription'], 'String');
      if (data.hasOwnProperty('Grant'))
        obj.grant = ApiClient.convertToType(data['Grant'], 'String');
      if (data.hasOwnProperty('Purpose'))
        obj.purpose = ApiClient.convertToType(data['Purpose'], 'String');
      if (data.hasOwnProperty('Description'))
        obj.description = ApiClient.convertToType(data['Description'], 'String');
      if (data.hasOwnProperty('Number'))
        obj._number = ApiClient.convertToType(data['Number'], 'Number');
      if (data.hasOwnProperty('Status'))
        obj.status = ApiClient.convertToType(data['Status'], 'String');
      if (data.hasOwnProperty('ManagedBy'))
        obj.managedBy = ApiClient.convertToType(data['ManagedBy'], 'String');
      if (data.hasOwnProperty('Date'))
        obj._date = ApiClient.convertToType(data['Date'], 'Date');
      if (data.hasOwnProperty('DateOfMeeting'))
        obj.dateOfMeeting = ApiClient.convertToType(data['DateOfMeeting'], 'Date');
      if (data.hasOwnProperty('DenialCode'))
        obj.denialCode = ApiClient.convertToType(data['DenialCode'], 'String');
      if (data.hasOwnProperty('DenialCodeDescription'))
        obj.denialCodeDescription = ApiClient.convertToType(data['DenialCodeDescription'], 'String');
      if (data.hasOwnProperty('Group'))
        obj.group = ApiClient.convertToType(data['Group'], 'String');
      if (data.hasOwnProperty('SubGroup'))
        obj.subGroup = ApiClient.convertToType(data['SubGroup'], 'String');
      if (data.hasOwnProperty('TotalAmount'))
        obj.totalAmount = ApiClient.convertToType(data['TotalAmount'], 'Number');
      if (data.hasOwnProperty('Period'))
        obj.period = DkCloudDataModelGeneralDateRange.constructFromObject(data['Period']);
      if (data.hasOwnProperty('Amount'))
        obj.amount = ApiClient.convertToType(data['Amount'], 'Number');
      if (data.hasOwnProperty('Posted'))
        obj.posted = ApiClient.convertToType(data['Posted'], 'Date');
      if (data.hasOwnProperty('Comment'))
        obj.comment = ApiClient.convertToType(data['Comment'], 'String');
      if (data.hasOwnProperty('Text1'))
        obj.text1 = ApiClient.convertToType(data['Text1'], 'String');
      if (data.hasOwnProperty('Text2'))
        obj.text2 = ApiClient.convertToType(data['Text2'], 'String');
      if (data.hasOwnProperty('MembershipRulesOK'))
        obj.membershipRulesOK = ApiClient.convertToType(data['MembershipRulesOK'], 'Boolean');
      if (data.hasOwnProperty('GrantRulesOK'))
        obj.grantRulesOK = ApiClient.convertToType(data['GrantRulesOK'], 'Boolean');
      if (data.hasOwnProperty('Reference'))
        obj.reference = ApiClient.convertToType(data['Reference'], 'String');
      if (data.hasOwnProperty('JobRatio'))
        obj.jobRatio = ApiClient.convertToType(data['JobRatio'], 'Number');
      if (data.hasOwnProperty('PeriodDesc'))
        obj.periodDesc = ApiClient.convertToType(data['PeriodDesc'], 'String');
      if (data.hasOwnProperty('CommunicationMemo'))
        obj.communicationMemo = ApiClient.convertToType(data['CommunicationMemo'], 'String');
      if (data.hasOwnProperty('GrantCount'))
        obj.grantCount = ApiClient.convertToType(data['GrantCount'], 'Number');
      if (data.hasOwnProperty('UnitCount'))
        obj.unitCount = ApiClient.convertToType(data['UnitCount'], 'Number');
      if (data.hasOwnProperty('Location'))
        obj.location = ApiClient.convertToType(data['Location'], 'String');
      if (data.hasOwnProperty('PeriodDescription'))
        obj.periodDescription = ApiClient.convertToType(data['PeriodDescription'], 'String');
      if (data.hasOwnProperty('Organizer'))
        obj.organizer = ApiClient.convertToType(data['Organizer'], 'String');
      if (data.hasOwnProperty('WorkPlace'))
        obj.workPlace = ApiClient.convertToType(data['WorkPlace'], 'String');
      if (data.hasOwnProperty('WorkPlaceNumber'))
        obj.workPlaceNumber = ApiClient.convertToType(data['WorkPlaceNumber'], 'String');
      if (data.hasOwnProperty('VoucherTag'))
        obj.voucherTag = ApiClient.convertToType(data['VoucherTag'], 'String');
      if (data.hasOwnProperty('Details'))
        obj.details = ApiClient.convertToType(data['Details'], [DkCloudDataModelMembersApplicationDetail]);
      if (data.hasOwnProperty('WorkPlaceHistory'))
        obj.workPlaceHistory = ApiClient.convertToType(data['WorkPlaceHistory'], [DkCloudDataModelMembersWorkPlaceHistory]);
      if (data.hasOwnProperty('MaternityLeaves'))
        obj.maternityLeaves = ApiClient.convertToType(data['MaternityLeaves'], [DkCloudDataModelMembersMaternityLeave]);
      if (data.hasOwnProperty('AmountTraveled'))
        obj.amountTraveled = ApiClient.convertToType(data['AmountTraveled'], 'Number');
      if (data.hasOwnProperty('TravelCost'))
        obj.travelCost = ApiClient.convertToType(data['TravelCost'], 'Number');
      if (data.hasOwnProperty('CompanyID'))
        obj.companyID = ApiClient.convertToType(data['CompanyID'], 'String');
      if (data.hasOwnProperty('Attachments'))
        obj.attachments = ApiClient.convertToType(data['Attachments'], [DkCloudDataModelGeneralAttachmentModel]);
      if (data.hasOwnProperty('TermsConsentGiven'))
        obj.termsConsentGiven = ApiClient.convertToType(data['TermsConsentGiven'], 'Boolean');
      if (data.hasOwnProperty('TermId'))
        obj.termId = ApiClient.convertToType(data['TermId'], 'Number');
      if (data.hasOwnProperty('ExtraProperties'))
        obj.extraProperties = ApiClient.convertToType(data['ExtraProperties'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * @member {String} member
   */
  exports.prototype.member = undefined;

  /**
   * @member {module:model/DkCloudDataModelMembersApplicationBankAccount} bankAccount
   */
  exports.prototype.bankAccount = undefined;

  /**
   * @member {module:model/DkCloudDataModelMembersApplicationContact} contact
   */
  exports.prototype.contact = undefined;

  /**
   * @member {String} fund
   */
  exports.prototype.fund = undefined;

  /**
   * @member {String} grantDescription
   */
  exports.prototype.grantDescription = undefined;

  /**
   * @member {String} grant
   */
  exports.prototype.grant = undefined;

  /**
   * @member {String} purpose
   */
  exports.prototype.purpose = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Number} _number
   */
  exports.prototype._number = undefined;

  /**
   * @member {module:model/DkCloudDataModelMembersApplication.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {module:model/DkCloudDataModelMembersApplication.ManagedByEnum} managedBy
   */
  exports.prototype.managedBy = undefined;

  /**
   * @member {Date} _date
   */
  exports.prototype._date = undefined;

  /**
   * @member {Date} dateOfMeeting
   */
  exports.prototype.dateOfMeeting = undefined;

  /**
   * @member {String} denialCode
   */
  exports.prototype.denialCode = undefined;

  /**
   * @member {String} denialCodeDescription
   */
  exports.prototype.denialCodeDescription = undefined;

  /**
   * @member {String} group
   */
  exports.prototype.group = undefined;

  /**
   * @member {String} subGroup
   */
  exports.prototype.subGroup = undefined;

  /**
   * @member {Number} totalAmount
   */
  exports.prototype.totalAmount = undefined;

  /**
   * @member {module:model/DkCloudDataModelGeneralDateRange} period
   */
  exports.prototype.period = undefined;

  /**
   * @member {Number} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {Date} posted
   */
  exports.prototype.posted = undefined;

  /**
   * @member {String} comment
   */
  exports.prototype.comment = undefined;

  /**
   * @member {String} text1
   */
  exports.prototype.text1 = undefined;

  /**
   * @member {String} text2
   */
  exports.prototype.text2 = undefined;

  /**
   * @member {Boolean} membershipRulesOK
   */
  exports.prototype.membershipRulesOK = undefined;

  /**
   * @member {Boolean} grantRulesOK
   */
  exports.prototype.grantRulesOK = undefined;

  /**
   * @member {String} reference
   */
  exports.prototype.reference = undefined;

  /**
   * @member {Number} jobRatio
   */
  exports.prototype.jobRatio = undefined;

  /**
   * @member {String} periodDesc
   */
  exports.prototype.periodDesc = undefined;

  /**
   * @member {String} communicationMemo
   */
  exports.prototype.communicationMemo = undefined;

  /**
   * @member {Number} grantCount
   */
  exports.prototype.grantCount = undefined;

  /**
   * @member {Number} unitCount
   */
  exports.prototype.unitCount = undefined;

  /**
   * @member {String} location
   */
  exports.prototype.location = undefined;

  /**
   * @member {String} periodDescription
   */
  exports.prototype.periodDescription = undefined;

  /**
   * @member {String} organizer
   */
  exports.prototype.organizer = undefined;

  /**
   * @member {String} workPlace
   */
  exports.prototype.workPlace = undefined;

  /**
   * @member {String} workPlaceNumber
   */
  exports.prototype.workPlaceNumber = undefined;

  /**
   * @member {String} voucherTag
   */
  exports.prototype.voucherTag = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelMembersApplicationDetail>} details
   */
  exports.prototype.details = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelMembersWorkPlaceHistory>} workPlaceHistory
   */
  exports.prototype.workPlaceHistory = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelMembersMaternityLeave>} maternityLeaves
   */
  exports.prototype.maternityLeaves = undefined;

  /**
   * @member {Number} amountTraveled
   */
  exports.prototype.amountTraveled = undefined;

  /**
   * @member {Number} travelCost
   */
  exports.prototype.travelCost = undefined;

  /**
   * @member {String} companyID
   */
  exports.prototype.companyID = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelGeneralAttachmentModel>} attachments
   */
  exports.prototype.attachments = undefined;

  /**
   * @member {Boolean} termsConsentGiven
   */
  exports.prototype.termsConsentGiven = undefined;

  /**
   * @member {Number} termId
   */
  exports.prototype.termId = undefined;

  /**
   * @member {Object.<String, String>} extraProperties
   */
  exports.prototype.extraProperties = undefined;



  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "InProgress"
     * @const
     */
    inProgress: "InProgress",

    /**
     * value: "Accepted"
     * @const
     */
    accepted: "Accepted",

    /**
     * value: "Rejected"
     * @const
     */
    rejected: "Rejected",

    /**
     * value: "Expired"
     * @const
     */
    expired: "Expired",

    /**
     * value: "PartlyPaid"
     * @const
     */
    partlyPaid: "PartlyPaid",

    /**
     * value: "FullyPaid"
     * @const
     */
    fullyPaid: "FullyPaid",

    /**
     * value: "Closed"
     * @const
     */
    closed: "Closed",

    /**
     * value: "PayedToCompany"
     * @const
     */
    payedToCompany: "PayedToCompany",

    /**
     * value: "OnHold"
     * @const
     */
    onHold: "OnHold",

    /**
     * value: "Invalid"
     * @const
     */
    invalid: "Invalid",

    /**
     * value: "NotFinished"
     * @const
     */
    notFinished: "NotFinished"
  };

  /**
   * Allowed values for the <code>managedBy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ManagedByEnum = {
    /**
     * value: "Employee"
     * @const
     */
    employee: "Employee",

    /**
     * value: "Meeting"
     * @const
     */
    meeting: "Meeting"
  };
  return exports;
}));
