/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelMembersFund'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelMembersFund'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelMembersMemberShipCompany = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelMembersFund);
  }
}(this, function(ApiClient, DkCloudDataModelMembersFund) {
  'use strict';

  /**
   * The DkCloudDataModelMembersMemberShipCompany model module.
   * @module model/DkCloudDataModelMembersMemberShipCompany
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelMembersMemberShipCompany</code>.
   * @alias module:model/DkCloudDataModelMembersMemberShipCompany
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelMembersMemberShipCompany</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelMembersMemberShipCompany} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelMembersMemberShipCompany} The populated <code>DkCloudDataModelMembersMemberShipCompany</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Number'))
        obj._number = ApiClient.convertToType(data['Number'], 'Number');
      if (data.hasOwnProperty('Code'))
        obj.code = ApiClient.convertToType(data['Code'], 'String');
      if (data.hasOwnProperty('Name'))
        obj.name = ApiClient.convertToType(data['Name'], 'String');
      if (data.hasOwnProperty('Funds'))
        obj.funds = ApiClient.convertToType(data['Funds'], [DkCloudDataModelMembersFund]);
    }
    return obj;
  }

  /**
   * @member {Number} _number
   */
  exports.prototype._number = undefined;

  /**
   * @member {String} code
   */
  exports.prototype.code = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelMembersFund>} funds
   */
  exports.prototype.funds = undefined;


  return exports;
}));
