/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelGeneralDateRange', 'model/DkCloudDataModelMembersPayment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelGeneralDateRange'), require('./DkCloudDataModelMembersPayment'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelMembersMemberFund = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelGeneralDateRange, root.DkPlusApi.DkCloudDataModelMembersPayment);
  }
}(this, function(ApiClient, DkCloudDataModelGeneralDateRange, DkCloudDataModelMembersPayment) {
  'use strict';

  /**
   * The DkCloudDataModelMembersMemberFund model module.
   * @module model/DkCloudDataModelMembersMemberFund
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelMembersMemberFund</code>.
   * @alias module:model/DkCloudDataModelMembersMemberFund
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelMembersMemberFund</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelMembersMemberFund} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelMembersMemberFund} The populated <code>DkCloudDataModelMembersMemberFund</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('BatchId'))
        obj.batchId = ApiClient.convertToType(data['BatchId'], 'Number');
      if (data.hasOwnProperty('JournalDate'))
        obj.journalDate = ApiClient.convertToType(data['JournalDate'], 'Date');
      if (data.hasOwnProperty('Period'))
        obj.period = DkCloudDataModelGeneralDateRange.constructFromObject(data['Period']);
      if (data.hasOwnProperty('Customer'))
        obj.customer = ApiClient.convertToType(data['Customer'], 'String');
      if (data.hasOwnProperty('WorkplaceId'))
        obj.workplaceId = ApiClient.convertToType(data['WorkplaceId'], 'String');
      if (data.hasOwnProperty('MembershipCompany'))
        obj.membershipCompany = ApiClient.convertToType(data['MembershipCompany'], 'String');
      if (data.hasOwnProperty('Reference'))
        obj.reference = ApiClient.convertToType(data['Reference'], 'String');
      if (data.hasOwnProperty('TotalAmount'))
        obj.totalAmount = ApiClient.convertToType(data['TotalAmount'], 'Number');
      if (data.hasOwnProperty('CustomerName'))
        obj.customerName = ApiClient.convertToType(data['CustomerName'], 'String');
      if (data.hasOwnProperty('Settled'))
        obj.settled = ApiClient.convertToType(data['Settled'], 'Boolean');
      if (data.hasOwnProperty('Payments'))
        obj.payments = ApiClient.convertToType(data['Payments'], [DkCloudDataModelMembersPayment]);
      if (data.hasOwnProperty('ExtraProperties'))
        obj.extraProperties = ApiClient.convertToType(data['ExtraProperties'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * @member {Number} batchId
   */
  exports.prototype.batchId = undefined;

  /**
   * @member {Date} journalDate
   */
  exports.prototype.journalDate = undefined;

  /**
   * @member {module:model/DkCloudDataModelGeneralDateRange} period
   */
  exports.prototype.period = undefined;

  /**
   * @member {String} customer
   */
  exports.prototype.customer = undefined;

  /**
   * @member {String} workplaceId
   */
  exports.prototype.workplaceId = undefined;

  /**
   * @member {String} membershipCompany
   */
  exports.prototype.membershipCompany = undefined;

  /**
   * @member {String} reference
   */
  exports.prototype.reference = undefined;

  /**
   * @member {Number} totalAmount
   */
  exports.prototype.totalAmount = undefined;

  /**
   * @member {String} customerName
   */
  exports.prototype.customerName = undefined;

  /**
   * @member {Boolean} settled
   */
  exports.prototype.settled = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelMembersPayment>} payments
   */
  exports.prototype.payments = undefined;

  /**
   * @member {Object.<String, String>} extraProperties
   */
  exports.prototype.extraProperties = undefined;


  return exports;
}));
