/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelGeneralDateRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelGeneralDateRange'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelMembersCareer = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelGeneralDateRange);
  }
}(this, function(ApiClient, DkCloudDataModelGeneralDateRange) {
  'use strict';

  /**
   * The DkCloudDataModelMembersCareer model module.
   * @module model/DkCloudDataModelMembersCareer
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelMembersCareer</code>.
   * @alias module:model/DkCloudDataModelMembersCareer
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelMembersCareer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelMembersCareer} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelMembersCareer} The populated <code>DkCloudDataModelMembersCareer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'Number');
      if (data.hasOwnProperty('Company'))
        obj.company = ApiClient.convertToType(data['Company'], 'String');
      if (data.hasOwnProperty('JobTitleCode'))
        obj.jobTitleCode = ApiClient.convertToType(data['JobTitleCode'], 'String');
      if (data.hasOwnProperty('JobTitle'))
        obj.jobTitle = ApiClient.convertToType(data['JobTitle'], 'String');
      if (data.hasOwnProperty('Period'))
        obj.period = DkCloudDataModelGeneralDateRange.constructFromObject(data['Period']);
      if (data.hasOwnProperty('WorkPercentage'))
        obj.workPercentage = ApiClient.convertToType(data['WorkPercentage'], 'Number');
      if (data.hasOwnProperty('Description'))
        obj.description = ApiClient.convertToType(data['Description'], 'String');
      if (data.hasOwnProperty('Workplace'))
        obj.workplace = ApiClient.convertToType(data['Workplace'], 'String');
      if (data.hasOwnProperty('WorkplaceName'))
        obj.workplaceName = ApiClient.convertToType(data['WorkplaceName'], 'String');
      if (data.hasOwnProperty('CompanyName'))
        obj.companyName = ApiClient.convertToType(data['CompanyName'], 'String');
      if (data.hasOwnProperty('ExtraProperties'))
        obj.extraProperties = ApiClient.convertToType(data['ExtraProperties'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * @member {Number} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {String} company
   */
  exports.prototype.company = undefined;

  /**
   * @member {String} jobTitleCode
   */
  exports.prototype.jobTitleCode = undefined;

  /**
   * @member {String} jobTitle
   */
  exports.prototype.jobTitle = undefined;

  /**
   * @member {module:model/DkCloudDataModelGeneralDateRange} period
   */
  exports.prototype.period = undefined;

  /**
   * @member {Number} workPercentage
   */
  exports.prototype.workPercentage = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} workplace
   */
  exports.prototype.workplace = undefined;

  /**
   * @member {String} workplaceName
   */
  exports.prototype.workplaceName = undefined;

  /**
   * @member {String} companyName
   */
  exports.prototype.companyName = undefined;

  /**
   * @member {Object.<String, String>} extraProperties
   */
  exports.prototype.extraProperties = undefined;


  return exports;
}));
