/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelCustomersCustomerModel', 'model/DkCloudDataModelCustomersItemReciverModel', 'model/DkCloudDataModelSalesSalesOrderLineModel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelCustomersCustomerModel'), require('./DkCloudDataModelCustomersItemReciverModel'), require('./DkCloudDataModelSalesSalesOrderLineModel'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelSalesSalesOrderModel = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelCustomersCustomerModel, root.DkPlusApi.DkCloudDataModelCustomersItemReciverModel, root.DkPlusApi.DkCloudDataModelSalesSalesOrderLineModel);
  }
}(this, function(ApiClient, DkCloudDataModelCustomersCustomerModel, DkCloudDataModelCustomersItemReciverModel, DkCloudDataModelSalesSalesOrderLineModel) {
  'use strict';

  /**
   * The DkCloudDataModelSalesSalesOrderModel model module.
   * @module model/DkCloudDataModelSalesSalesOrderModel
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelSalesSalesOrderModel</code>.
   * @alias module:model/DkCloudDataModelSalesSalesOrderModel
   * @class
   * @param customer {module:model/DkCloudDataModelCustomersCustomerModel} 
   */
  var exports = function(customer) {
    this.customer = customer;
  };

  /**
   * Constructs a <code>DkCloudDataModelSalesSalesOrderModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelSalesSalesOrderModel} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelSalesSalesOrderModel} The populated <code>DkCloudDataModelSalesSalesOrderModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Number'))
        obj._number = ApiClient.convertToType(data['Number'], 'Number');
      if (data.hasOwnProperty('Customer'))
        obj.customer = DkCloudDataModelCustomersCustomerModel.constructFromObject(data['Customer']);
      if (data.hasOwnProperty('CContact'))
        obj.cContact = ApiClient.convertToType(data['CContact'], 'String');
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'Number');
      if (data.hasOwnProperty('OrderDate'))
        obj.orderDate = ApiClient.convertToType(data['OrderDate'], 'Date');
      if (data.hasOwnProperty('CustomerOrderDate'))
        obj.customerOrderDate = ApiClient.convertToType(data['CustomerOrderDate'], 'Date');
      if (data.hasOwnProperty('CustomerOrderNumber'))
        obj.customerOrderNumber = ApiClient.convertToType(data['CustomerOrderNumber'], 'String');
      if (data.hasOwnProperty('TotalAmount'))
        obj.totalAmount = ApiClient.convertToType(data['TotalAmount'], 'Number');
      if (data.hasOwnProperty('Currency'))
        obj.currency = ApiClient.convertToType(data['Currency'], 'String');
      if (data.hasOwnProperty('Reference'))
        obj.reference = ApiClient.convertToType(data['Reference'], 'String');
      if (data.hasOwnProperty('SettledType'))
        obj.settledType = ApiClient.convertToType(data['SettledType'], 'Number');
      if (data.hasOwnProperty('SettledAmount'))
        obj.settledAmount = ApiClient.convertToType(data['SettledAmount'], 'Number');
      if (data.hasOwnProperty('SalePerson'))
        obj.salePerson = ApiClient.convertToType(data['SalePerson'], 'String');
      if (data.hasOwnProperty('Text1'))
        obj.text1 = ApiClient.convertToType(data['Text1'], 'String');
      if (data.hasOwnProperty('Text2'))
        obj.text2 = ApiClient.convertToType(data['Text2'], 'String');
      if (data.hasOwnProperty('Dim1'))
        obj.dim1 = ApiClient.convertToType(data['Dim1'], 'String');
      if (data.hasOwnProperty('Origin'))
        obj.origin = ApiClient.convertToType(data['Origin'], 'Number');
      if (data.hasOwnProperty('PaymentTerm'))
        obj.paymentTerm = ApiClient.convertToType(data['PaymentTerm'], 'String');
      if (data.hasOwnProperty('ClaimStatus'))
        obj.claimStatus = ApiClient.convertToType(data['ClaimStatus'], 'Number');
      if (data.hasOwnProperty('Exchange'))
        obj.exchange = ApiClient.convertToType(data['Exchange'], 'Number');
      if (data.hasOwnProperty('Status'))
        obj.status = ApiClient.convertToType(data['Status'], 'String');
      if (data.hasOwnProperty('DeliveryStatus'))
        obj.deliveryStatus = ApiClient.convertToType(data['DeliveryStatus'], 'String');
      if (data.hasOwnProperty('DeliverTo'))
        obj.deliverTo = DkCloudDataModelCustomersItemReciverModel.constructFromObject(data['DeliverTo']);
      if (data.hasOwnProperty('Lines'))
        obj.lines = ApiClient.convertToType(data['Lines'], [DkCloudDataModelSalesSalesOrderLineModel]);
    }
    return obj;
  }

  /**
   * @member {Number} _number
   */
  exports.prototype._number = undefined;

  /**
   * @member {module:model/DkCloudDataModelCustomersCustomerModel} customer
   */
  exports.prototype.customer = undefined;

  /**
   * @member {String} cContact
   */
  exports.prototype.cContact = undefined;

  /**
   * @member {Number} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {Date} orderDate
   */
  exports.prototype.orderDate = undefined;

  /**
   * @member {Date} customerOrderDate
   */
  exports.prototype.customerOrderDate = undefined;

  /**
   * @member {String} customerOrderNumber
   */
  exports.prototype.customerOrderNumber = undefined;

  /**
   * @member {Number} totalAmount
   */
  exports.prototype.totalAmount = undefined;

  /**
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * @member {String} reference
   */
  exports.prototype.reference = undefined;

  /**
   * @member {Number} settledType
   */
  exports.prototype.settledType = undefined;

  /**
   * @member {Number} settledAmount
   */
  exports.prototype.settledAmount = undefined;

  /**
   * @member {String} salePerson
   */
  exports.prototype.salePerson = undefined;

  /**
   * @member {String} text1
   */
  exports.prototype.text1 = undefined;

  /**
   * @member {String} text2
   */
  exports.prototype.text2 = undefined;

  /**
   * @member {String} dim1
   */
  exports.prototype.dim1 = undefined;

  /**
   * @member {Number} origin
   */
  exports.prototype.origin = undefined;

  /**
   * @member {String} paymentTerm
   */
  exports.prototype.paymentTerm = undefined;

  /**
   * @member {Number} claimStatus
   */
  exports.prototype.claimStatus = undefined;

  /**
   * @member {Number} exchange
   */
  exports.prototype.exchange = undefined;

  /**
   * @member {module:model/DkCloudDataModelSalesSalesOrderModel.StatusEnum} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {module:model/DkCloudDataModelSalesSalesOrderModel.DeliveryStatusEnum} deliveryStatus
   */
  exports.prototype.deliveryStatus = undefined;

  /**
   * @member {module:model/DkCloudDataModelCustomersItemReciverModel} deliverTo
   */
  exports.prototype.deliverTo = undefined;

  /**
   * @member {Array.<module:model/DkCloudDataModelSalesSalesOrderLineModel>} lines
   */
  exports.prototype.lines = undefined;



  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "InProcess"
     * @const
     */
    inProcess: "InProcess",

    /**
     * value: "Sent"
     * @const
     */
    sent: "Sent",

    /**
     * value: "PartHandled"
     * @const
     */
    partHandled: "PartHandled",

    /**
     * value: "Handled"
     * @const
     */
    handled: "Handled",

    /**
     * value: "OnHold"
     * @const
     */
    onHold: "OnHold",

    /**
     * value: "Canceled"
     * @const
     */
    canceled: "Canceled"
  };

  /**
   * Allowed values for the <code>deliveryStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DeliveryStatusEnum = {
    /**
     * value: "InProcess"
     * @const
     */
    inProcess: "InProcess",

    /**
     * value: "Ready"
     * @const
     */
    ready: "Ready",

    /**
     * value: "Hurry"
     * @const
     */
    hurry: "Hurry",

    /**
     * value: "Wait"
     * @const
     */
    wait: "Wait",

    /**
     * value: "Request"
     * @const
     */
    request: "Request"
  };
  return exports;
}));
