/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkCloudDataModelUserTokenModel = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkCloudDataModelUserTokenModel model module.
   * @module model/DkCloudDataModelUserTokenModel
   * @version v1
   */

  /**
   * Constructs a new <code>DkCloudDataModelUserTokenModel</code>.
   * @alias module:model/DkCloudDataModelUserTokenModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkCloudDataModelUserTokenModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkCloudDataModelUserTokenModel} obj Optional instance to populate.
   * @return {module:model/DkCloudDataModelUserTokenModel} The populated <code>DkCloudDataModelUserTokenModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Token'))
        obj.token = ApiClient.convertToType(data['Token'], 'String');
      if (data.hasOwnProperty('Company'))
        obj.company = ApiClient.convertToType(data['Company'], 'String');
      if (data.hasOwnProperty('User'))
        obj.user = ApiClient.convertToType(data['User'], 'String');
      if (data.hasOwnProperty('Type'))
        obj.type = ApiClient.convertToType(data['Type'], 'String');
      if (data.hasOwnProperty('Description'))
        obj.description = ApiClient.convertToType(data['Description'], 'String');
      if (data.hasOwnProperty('Notify'))
        obj.notify = ApiClient.convertToType(data['Notify'], ['String']);
    }
    return obj;
  }

  /**
   * @member {String} token
   */
  exports.prototype.token = undefined;

  /**
   * @member {String} company
   */
  exports.prototype.company = undefined;

  /**
   * @member {String} user
   */
  exports.prototype.user = undefined;

  /**
   * @member {module:model/DkCloudDataModelUserTokenModel.TypeEnum} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Array.<String>} notify
   */
  exports.prototype.notify = undefined;



  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "General"
     * @const
     */
    general: "General",

    /**
     * value: "Bokun"
     * @const
     */
    bokun: "Bokun"
  };
  return exports;
}));
