/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkPlusAPIModelsProductInventoryInventoryingLine'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkPlusAPIModelsProductInventoryInventoryingLine'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkPlusAPIModelsProductInventoryInventorying = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkPlusAPIModelsProductInventoryInventoryingLine);
  }
}(this, function(ApiClient, DkPlusAPIModelsProductInventoryInventoryingLine) {
  'use strict';

  /**
   * The DkPlusAPIModelsProductInventoryInventorying model module.
   * @module model/DkPlusAPIModelsProductInventoryInventorying
   * @version v1
   */

  /**
   * Constructs a new <code>DkPlusAPIModelsProductInventoryInventorying</code>.
   * @alias module:model/DkPlusAPIModelsProductInventoryInventorying
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkPlusAPIModelsProductInventoryInventorying</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkPlusAPIModelsProductInventoryInventorying} obj Optional instance to populate.
   * @return {module:model/DkPlusAPIModelsProductInventoryInventorying} The populated <code>DkPlusAPIModelsProductInventoryInventorying</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Description'))
        obj.description = ApiClient.convertToType(data['Description'], 'String');
      if (data.hasOwnProperty('Lines'))
        obj.lines = ApiClient.convertToType(data['Lines'], [DkPlusAPIModelsProductInventoryInventoryingLine]);
    }
    return obj;
  }

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {Array.<module:model/DkPlusAPIModelsProductInventoryInventoryingLine>} lines
   */
  exports.prototype.lines = undefined;


  return exports;
}));
