/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkPlusAPIModelsInvoicePaymentPlanCard = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DkPlusAPIModelsInvoicePaymentPlanCard model module.
   * @module model/DkPlusAPIModelsInvoicePaymentPlanCard
   * @version v1
   */

  /**
   * Constructs a new <code>DkPlusAPIModelsInvoicePaymentPlanCard</code>.
   * Card Information
   * @alias module:model/DkPlusAPIModelsInvoicePaymentPlanCard
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkPlusAPIModelsInvoicePaymentPlanCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkPlusAPIModelsInvoicePaymentPlanCard} obj Optional instance to populate.
   * @return {module:model/DkPlusAPIModelsInvoicePaymentPlanCard} The populated <code>DkPlusAPIModelsInvoicePaymentPlanCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Number'))
        obj._number = ApiClient.convertToType(data['Number'], 'String');
      if (data.hasOwnProperty('Type'))
        obj.type = ApiClient.convertToType(data['Type'], 'String');
    }
    return obj;
  }

  /**
   * Car Number
   * @member {String} _number
   */
  exports.prototype._number = undefined;

  /**
   * Card Type
   * @member {String} type
   */
  exports.prototype.type = undefined;


  return exports;
}));
