/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkPlusAPIModelsInvoiceVariation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkPlusAPIModelsInvoiceVariation'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkPlusAPIModelsSubscriptionSubscriptionLine = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkPlusAPIModelsInvoiceVariation);
  }
}(this, function(ApiClient, DkPlusAPIModelsInvoiceVariation) {
  'use strict';

  /**
   * The DkPlusAPIModelsSubscriptionSubscriptionLine model module.
   * @module model/DkPlusAPIModelsSubscriptionSubscriptionLine
   * @version v1
   */

  /**
   * Constructs a new <code>DkPlusAPIModelsSubscriptionSubscriptionLine</code>.
   * @alias module:model/DkPlusAPIModelsSubscriptionSubscriptionLine
   * @class
   * @param itemCode {String} Product Item Code
   */
  var exports = function(itemCode) {
    this.itemCode = itemCode;
  };

  /**
   * Constructs a <code>DkPlusAPIModelsSubscriptionSubscriptionLine</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkPlusAPIModelsSubscriptionSubscriptionLine} obj Optional instance to populate.
   * @return {module:model/DkPlusAPIModelsSubscriptionSubscriptionLine} The populated <code>DkPlusAPIModelsSubscriptionSubscriptionLine</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ItemCode'))
        obj.itemCode = ApiClient.convertToType(data['ItemCode'], 'String');
      if (data.hasOwnProperty('Warehouse'))
        obj.warehouse = ApiClient.convertToType(data['Warehouse'], 'String');
      if (data.hasOwnProperty('Text'))
        obj.text = ApiClient.convertToType(data['Text'], 'String');
      if (data.hasOwnProperty('Text2'))
        obj.text2 = ApiClient.convertToType(data['Text2'], 'String');
      if (data.hasOwnProperty('Quantity'))
        obj.quantity = ApiClient.convertToType(data['Quantity'], 'Number');
      if (data.hasOwnProperty('Reference'))
        obj.reference = ApiClient.convertToType(data['Reference'], 'String');
      if (data.hasOwnProperty('IncludingVAT'))
        obj.includingVAT = ApiClient.convertToType(data['IncludingVAT'], 'Boolean');
      if (data.hasOwnProperty('Price'))
        obj.price = ApiClient.convertToType(data['Price'], 'Number');
      if (data.hasOwnProperty('Discount'))
        obj.discount = ApiClient.convertToType(data['Discount'], 'Number');
      if (data.hasOwnProperty('DiscountAmount'))
        obj.discountAmount = ApiClient.convertToType(data['DiscountAmount'], 'Number');
      if (data.hasOwnProperty('Total'))
        obj.total = ApiClient.convertToType(data['Total'], 'Number');
      if (data.hasOwnProperty('Dim1'))
        obj.dim1 = ApiClient.convertToType(data['Dim1'], 'String');
      if (data.hasOwnProperty('Memo'))
        obj.memo = ApiClient.convertToType(data['Memo'], 'String');
      if (data.hasOwnProperty('Variations'))
        obj.variations = ApiClient.convertToType(data['Variations'], [DkPlusAPIModelsInvoiceVariation]);
      if (data.hasOwnProperty('Properties'))
        obj.properties = ApiClient.convertToType(data['Properties'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * Product Item Code
   * @member {String} itemCode
   */
  exports.prototype.itemCode = undefined;

  /**
   * Product Warehouse
   * @member {String} warehouse
   */
  exports.prototype.warehouse = undefined;

  /**
   * Text
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * Text 2
   * @member {String} text2
   */
  exports.prototype.text2 = undefined;

  /**
   * Quantity
   * @member {Number} quantity
   */
  exports.prototype.quantity = undefined;

  /**
   * Reference
   * @member {String} reference
   */
  exports.prototype.reference = undefined;

  /**
   * Prices include VAT
   * @member {Boolean} includingVAT
   */
  exports.prototype.includingVAT = undefined;

  /**
   * Unit Price
   * @member {Number} price
   */
  exports.prototype.price = undefined;

  /**
   * Discount Percent
   * @member {Number} discount
   */
  exports.prototype.discount = undefined;

  /**
   * Discount Amount
   * @member {Number} discountAmount
   */
  exports.prototype.discountAmount = undefined;

  /**
   * Line Total Amount
   * @member {Number} total
   */
  exports.prototype.total = undefined;

  /**
   * Dimmention
   * @member {String} dim1
   */
  exports.prototype.dim1 = undefined;

  /**
   * 
   * @member {String} memo
   */
  exports.prototype.memo = undefined;

  /**
   * Production Variations
   * @member {Array.<module:model/DkPlusAPIModelsInvoiceVariation>} variations
   */
  exports.prototype.variations = undefined;

  /**
   * Line additional properties
   * @member {Object.<String, String>} properties
   */
  exports.prototype.properties = undefined;


  return exports;
}));
