/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DkCloudDataModelVendorsVendorBaseModel', 'model/DkPlusAPIModelsPurchaseLine'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DkCloudDataModelVendorsVendorBaseModel'), require('./DkPlusAPIModelsPurchaseLine'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.DkPlusAPIModelsPurchaseHead = factory(root.DkPlusApi.ApiClient, root.DkPlusApi.DkCloudDataModelVendorsVendorBaseModel, root.DkPlusApi.DkPlusAPIModelsPurchaseLine);
  }
}(this, function(ApiClient, DkCloudDataModelVendorsVendorBaseModel, DkPlusAPIModelsPurchaseLine) {
  'use strict';

  /**
   * The DkPlusAPIModelsPurchaseHead model module.
   * @module model/DkPlusAPIModelsPurchaseHead
   * @version v1
   */

  /**
   * Constructs a new <code>DkPlusAPIModelsPurchaseHead</code>.
   * @alias module:model/DkPlusAPIModelsPurchaseHead
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DkPlusAPIModelsPurchaseHead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DkPlusAPIModelsPurchaseHead} obj Optional instance to populate.
   * @return {module:model/DkPlusAPIModelsPurchaseHead} The populated <code>DkPlusAPIModelsPurchaseHead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('Number'))
        obj._number = ApiClient.convertToType(data['Number'], 'String');
      if (data.hasOwnProperty('Reference'))
        obj.reference = ApiClient.convertToType(data['Reference'], 'String');
      if (data.hasOwnProperty('Vendor'))
        obj.vendor = DkCloudDataModelVendorsVendorBaseModel.constructFromObject(data['Vendor']);
      if (data.hasOwnProperty('OrderDate'))
        obj.orderDate = ApiClient.convertToType(data['OrderDate'], 'Date');
      if (data.hasOwnProperty('Lines'))
        obj.lines = ApiClient.convertToType(data['Lines'], [DkPlusAPIModelsPurchaseLine]);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} _number
   */
  exports.prototype._number = undefined;

  /**
   * @member {String} reference
   */
  exports.prototype.reference = undefined;

  /**
   * @member {module:model/DkCloudDataModelVendorsVendorBaseModel} vendor
   */
  exports.prototype.vendor = undefined;

  /**
   * @member {Date} orderDate
   */
  exports.prototype.orderDate = undefined;

  /**
   * @member {Array.<module:model/DkPlusAPIModelsPurchaseLine>} lines
   */
  exports.prototype.lines = undefined;


  return exports;
}));
