/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DkPlusApi) {
      root.DkPlusApi = {};
    }
    root.DkPlusApi.SystemWebMvcFileContentResult = factory(root.DkPlusApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SystemWebMvcFileContentResult model module.
   * @module model/SystemWebMvcFileContentResult
   * @version v1
   */

  /**
   * Constructs a new <code>SystemWebMvcFileContentResult</code>.
   * @alias module:model/SystemWebMvcFileContentResult
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SystemWebMvcFileContentResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SystemWebMvcFileContentResult} obj Optional instance to populate.
   * @return {module:model/SystemWebMvcFileContentResult} The populated <code>SystemWebMvcFileContentResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('FileContents'))
        obj.fileContents = ApiClient.convertToType(data['FileContents'], 'Blob');
      if (data.hasOwnProperty('ContentType'))
        obj.contentType = ApiClient.convertToType(data['ContentType'], 'String');
      if (data.hasOwnProperty('FileDownloadName'))
        obj.fileDownloadName = ApiClient.convertToType(data['FileDownloadName'], 'String');
    }
    return obj;
  }

  /**
   * @member {Blob} fileContents
   */
  exports.prototype.fileContents = undefined;

  /**
   * @member {String} contentType
   */
  exports.prototype.contentType = undefined;

  /**
   * @member {String} fileDownloadName
   */
  exports.prototype.fileDownloadName = undefined;


  return exports;
}));
