/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkCloudDataModelMembersPayment', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkCloudDataModelMembersPayment();
      });

      it('should create an instance of DkCloudDataModelMembersPayment', function() {
        // TODO: update the code to test DkCloudDataModelMembersPayment
        expect(instance).to.be.a(DkPlusApi.DkCloudDataModelMembersPayment);
      });

      it('should have the property fundCode (base name: "FundCode")', function() {
        // TODO: update the code to test the property fundCode
        expect(instance).to.have.property('fundCode');
        // expect(instance.fundCode).to.be(expectedValueLiteral);
      });

      it('should have the property fundName (base name: "FundName")', function() {
        // TODO: update the code to test the property fundName
        expect(instance).to.have.property('fundName');
        // expect(instance.fundName).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "Amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property extraProperties (base name: "ExtraProperties")', function() {
        // TODO: update the code to test the property extraProperties
        expect(instance).to.have.property('extraProperties');
        // expect(instance.extraProperties).to.be(expectedValueLiteral);
      });

    });
  });

}));
