/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkCloudDataModelSettingsProjectSetting', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkCloudDataModelSettingsProjectSetting();
      });

      it('should create an instance of DkCloudDataModelSettingsProjectSetting', function() {
        // TODO: update the code to test DkCloudDataModelSettingsProjectSetting
        expect(instance).to.be.a(DkPlusApi.DkCloudDataModelSettingsProjectSetting);
      });

      it('should have the property enabled (base name: "Enabled")', function() {
        // TODO: update the code to test the property enabled
        expect(instance).to.have.property('enabled');
        // expect(instance.enabled).to.be(expectedValueLiteral);
      });

      it('should have the property phaseEnabled (base name: "PhaseEnabled")', function() {
        // TODO: update the code to test the property phaseEnabled
        expect(instance).to.have.property('phaseEnabled');
        // expect(instance.phaseEnabled).to.be(expectedValueLiteral);
      });

      it('should have the property taskEnabled (base name: "TaskEnabled")', function() {
        // TODO: update the code to test the property taskEnabled
        expect(instance).to.have.property('taskEnabled');
        // expect(instance.taskEnabled).to.be(expectedValueLiteral);
      });

      it('should have the property enterDriveInJournal (base name: "EnterDriveInJournal")', function() {
        // TODO: update the code to test the property enterDriveInJournal
        expect(instance).to.have.property('enterDriveInJournal');
        // expect(instance.enterDriveInJournal).to.be(expectedValueLiteral);
      });

      it('should have the property defaultDriveUnit (base name: "DefaultDriveUnit")', function() {
        // TODO: update the code to test the property defaultDriveUnit
        expect(instance).to.have.property('defaultDriveUnit');
        // expect(instance.defaultDriveUnit).to.be(expectedValueLiteral);
      });

    });
  });

}));
