/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkCloudDataModelVendorsVendorModel', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkCloudDataModelVendorsVendorModel();
      });

      it('should create an instance of DkCloudDataModelVendorsVendorModel', function() {
        // TODO: update the code to test DkCloudDataModelVendorsVendorModel
        expect(instance).to.be.a(DkPlusApi.DkCloudDataModelVendorsVendorModel);
      });

      it('should have the property _number (base name: "Number")', function() {
        // TODO: update the code to test the property _number
        expect(instance).to.have.property('_number');
        // expect(instance._number).to.be(expectedValueLiteral);
      });

      it('should have the property recordID (base name: "RecordID")', function() {
        // TODO: update the code to test the property recordID
        expect(instance).to.have.property('recordID');
        // expect(instance.recordID).to.be(expectedValueLiteral);
      });

      it('should have the property created (base name: "Created")', function() {
        // TODO: update the code to test the property created
        expect(instance).to.have.property('created');
        // expect(instance.created).to.be(expectedValueLiteral);
      });

      it('should have the property modified (base name: "Modified")', function() {
        // TODO: update the code to test the property modified
        expect(instance).to.have.property('modified');
        // expect(instance.modified).to.be(expectedValueLiteral);
      });

      it('should have the property sSNumber (base name: "SSNumber")', function() {
        // TODO: update the code to test the property sSNumber
        expect(instance).to.have.property('sSNumber');
        // expect(instance.sSNumber).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "Name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property address1 (base name: "Address1")', function() {
        // TODO: update the code to test the property address1
        expect(instance).to.have.property('address1');
        // expect(instance.address1).to.be(expectedValueLiteral);
      });

      it('should have the property address2 (base name: "Address2")', function() {
        // TODO: update the code to test the property address2
        expect(instance).to.have.property('address2');
        // expect(instance.address2).to.be(expectedValueLiteral);
      });

      it('should have the property address3 (base name: "Address3")', function() {
        // TODO: update the code to test the property address3
        expect(instance).to.have.property('address3');
        // expect(instance.address3).to.be(expectedValueLiteral);
      });

      it('should have the property address4 (base name: "Address4")', function() {
        // TODO: update the code to test the property address4
        expect(instance).to.have.property('address4');
        // expect(instance.address4).to.be(expectedValueLiteral);
      });

      it('should have the property group (base name: "Group")', function() {
        // TODO: update the code to test the property group
        expect(instance).to.have.property('group');
        // expect(instance.group).to.be(expectedValueLiteral);
      });

      it('should have the property tag (base name: "Tag")', function() {
        // TODO: update the code to test the property tag
        expect(instance).to.have.property('tag');
        // expect(instance.tag).to.be(expectedValueLiteral);
      });

      it('should have the property blocked (base name: "Blocked")', function() {
        // TODO: update the code to test the property blocked
        expect(instance).to.have.property('blocked');
        // expect(instance.blocked).to.be(expectedValueLiteral);
      });

      it('should have the property approve (base name: "Approve")', function() {
        // TODO: update the code to test the property approve
        expect(instance).to.have.property('approve');
        // expect(instance.approve).to.be(expectedValueLiteral);
      });

      it('should have the property creditMax (base name: "CreditMax")', function() {
        // TODO: update the code to test the property creditMax
        expect(instance).to.have.property('creditMax');
        // expect(instance.creditMax).to.be(expectedValueLiteral);
      });

      it('should have the property creditLimit (base name: "CreditLimit")', function() {
        // TODO: update the code to test the property creditLimit
        expect(instance).to.have.property('creditLimit');
        // expect(instance.creditLimit).to.be(expectedValueLiteral);
      });

      it('should have the property bankInfo (base name: "BankInfo")', function() {
        // TODO: update the code to test the property bankInfo
        expect(instance).to.have.property('bankInfo');
        // expect(instance.bankInfo).to.be(expectedValueLiteral);
      });

      it('should have the property handleBankInfo (base name: "HandleBankInfo")', function() {
        // TODO: update the code to test the property handleBankInfo
        expect(instance).to.have.property('handleBankInfo');
        // expect(instance.handleBankInfo).to.be(expectedValueLiteral);
      });

      it('should have the property zipCode (base name: "ZipCode")', function() {
        // TODO: update the code to test the property zipCode
        expect(instance).to.have.property('zipCode');
        // expect(instance.zipCode).to.be(expectedValueLiteral);
      });

      it('should have the property city (base name: "City")', function() {
        // TODO: update the code to test the property city
        expect(instance).to.have.property('city');
        // expect(instance.city).to.be(expectedValueLiteral);
      });

      it('should have the property phone (base name: "Phone")', function() {
        // TODO: update the code to test the property phone
        expect(instance).to.have.property('phone');
        // expect(instance.phone).to.be(expectedValueLiteral);
      });

      it('should have the property phoneLocal (base name: "PhoneLocal")', function() {
        // TODO: update the code to test the property phoneLocal
        expect(instance).to.have.property('phoneLocal');
        // expect(instance.phoneLocal).to.be(expectedValueLiteral);
      });

      it('should have the property phoneMobile (base name: "PhoneMobile")', function() {
        // TODO: update the code to test the property phoneMobile
        expect(instance).to.have.property('phoneMobile');
        // expect(instance.phoneMobile).to.be(expectedValueLiteral);
      });

      it('should have the property fax (base name: "Fax")', function() {
        // TODO: update the code to test the property fax
        expect(instance).to.have.property('fax');
        // expect(instance.fax).to.be(expectedValueLiteral);
      });

      it('should have the property countryCode (base name: "CountryCode")', function() {
        // TODO: update the code to test the property countryCode
        expect(instance).to.have.property('countryCode');
        // expect(instance.countryCode).to.be(expectedValueLiteral);
      });

      it('should have the property countyCode (base name: "CountyCode")', function() {
        // TODO: update the code to test the property countyCode
        expect(instance).to.have.property('countyCode');
        // expect(instance.countyCode).to.be(expectedValueLiteral);
      });

      it('should have the property email (base name: "Email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property discount (base name: "Discount")', function() {
        // TODO: update the code to test the property discount
        expect(instance).to.have.property('discount');
        // expect(instance.discount).to.be(expectedValueLiteral);
      });

      it('should have the property paymentMode (base name: "PaymentMode")', function() {
        // TODO: update the code to test the property paymentMode
        expect(instance).to.have.property('paymentMode');
        // expect(instance.paymentMode).to.be(expectedValueLiteral);
      });

      it('should have the property paymentTerm (base name: "PaymentTerm")', function() {
        // TODO: update the code to test the property paymentTerm
        expect(instance).to.have.property('paymentTerm');
        // expect(instance.paymentTerm).to.be(expectedValueLiteral);
      });

      it('should have the property currencyCode (base name: "CurrencyCode")', function() {
        // TODO: update the code to test the property currencyCode
        expect(instance).to.have.property('currencyCode');
        // expect(instance.currencyCode).to.be(expectedValueLiteral);
      });

      it('should have the property currencyFixed (base name: "CurrencyFixed")', function() {
        // TODO: update the code to test the property currencyFixed
        expect(instance).to.have.property('currencyFixed');
        // expect(instance.currencyFixed).to.be(expectedValueLiteral);
      });

      it('should have the property useCurrency (base name: "UseCurrency")', function() {
        // TODO: update the code to test the property useCurrency
        expect(instance).to.have.property('useCurrency');
        // expect(instance.useCurrency).to.be(expectedValueLiteral);
      });

      it('should have the property noVat (base name: "NoVat")', function() {
        // TODO: update the code to test the property noVat
        expect(instance).to.have.property('noVat');
        // expect(instance.noVat).to.be(expectedValueLiteral);
      });

      it('should have the property vATNumber (base name: "VATNumber")', function() {
        // TODO: update the code to test the property vATNumber
        expect(instance).to.have.property('vATNumber');
        // expect(instance.vATNumber).to.be(expectedValueLiteral);
      });

      it('should have the property disableTax (base name: "DisableTax")', function() {
        // TODO: update the code to test the property disableTax
        expect(instance).to.have.property('disableTax');
        // expect(instance.disableTax).to.be(expectedValueLiteral);
      });

      it('should have the property ledgerCode (base name: "LedgerCode")', function() {
        // TODO: update the code to test the property ledgerCode
        expect(instance).to.have.property('ledgerCode');
        // expect(instance.ledgerCode).to.be(expectedValueLiteral);
      });

      it('should have the property balance (base name: "Balance")', function() {
        // TODO: update the code to test the property balance
        expect(instance).to.have.property('balance');
        // expect(instance.balance).to.be(expectedValueLiteral);
      });

      it('should have the property dimmentions (base name: "Dimmentions")', function() {
        // TODO: update the code to test the property dimmentions
        expect(instance).to.have.property('dimmentions');
        // expect(instance.dimmentions).to.be(expectedValueLiteral);
      });

      it('should have the property expenses (base name: "Expenses")', function() {
        // TODO: update the code to test the property expenses
        expect(instance).to.have.property('expenses');
        // expect(instance.expenses).to.be(expectedValueLiteral);
      });

      it('should have the property attachments (base name: "Attachments")', function() {
        // TODO: update the code to test the property attachments
        expect(instance).to.have.property('attachments');
        // expect(instance.attachments).to.be(expectedValueLiteral);
      });

      it('should have the property memos (base name: "Memos")', function() {
        // TODO: update the code to test the property memos
        expect(instance).to.have.property('memos');
        // expect(instance.memos).to.be(expectedValueLiteral);
      });

    });
  });

}));
