/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkCloudDataModelMembersCareer', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkCloudDataModelMembersCareer();
      });

      it('should create an instance of DkCloudDataModelMembersCareer', function() {
        // TODO: update the code to test DkCloudDataModelMembersCareer
        expect(instance).to.be.a(DkPlusApi.DkCloudDataModelMembersCareer);
      });

      it('should have the property ID (base name: "ID")', function() {
        // TODO: update the code to test the property ID
        expect(instance).to.have.property('ID');
        // expect(instance.ID).to.be(expectedValueLiteral);
      });

      it('should have the property company (base name: "Company")', function() {
        // TODO: update the code to test the property company
        expect(instance).to.have.property('company');
        // expect(instance.company).to.be(expectedValueLiteral);
      });

      it('should have the property jobTitleCode (base name: "JobTitleCode")', function() {
        // TODO: update the code to test the property jobTitleCode
        expect(instance).to.have.property('jobTitleCode');
        // expect(instance.jobTitleCode).to.be(expectedValueLiteral);
      });

      it('should have the property jobTitle (base name: "JobTitle")', function() {
        // TODO: update the code to test the property jobTitle
        expect(instance).to.have.property('jobTitle');
        // expect(instance.jobTitle).to.be(expectedValueLiteral);
      });

      it('should have the property period (base name: "Period")', function() {
        // TODO: update the code to test the property period
        expect(instance).to.have.property('period');
        // expect(instance.period).to.be(expectedValueLiteral);
      });

      it('should have the property workPercentage (base name: "WorkPercentage")', function() {
        // TODO: update the code to test the property workPercentage
        expect(instance).to.have.property('workPercentage');
        // expect(instance.workPercentage).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "Description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property workplace (base name: "Workplace")', function() {
        // TODO: update the code to test the property workplace
        expect(instance).to.have.property('workplace');
        // expect(instance.workplace).to.be(expectedValueLiteral);
      });

      it('should have the property workplaceName (base name: "WorkplaceName")', function() {
        // TODO: update the code to test the property workplaceName
        expect(instance).to.have.property('workplaceName');
        // expect(instance.workplaceName).to.be(expectedValueLiteral);
      });

      it('should have the property companyName (base name: "CompanyName")', function() {
        // TODO: update the code to test the property companyName
        expect(instance).to.have.property('companyName');
        // expect(instance.companyName).to.be(expectedValueLiteral);
      });

      it('should have the property extraProperties (base name: "ExtraProperties")', function() {
        // TODO: update the code to test the property extraProperties
        expect(instance).to.have.property('extraProperties');
        // expect(instance.extraProperties).to.be(expectedValueLiteral);
      });

    });
  });

}));
