/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkCloudDataModelGeneralCreditCard', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkCloudDataModelGeneralCreditCard();
      });

      it('should create an instance of DkCloudDataModelGeneralCreditCard', function() {
        // TODO: update the code to test DkCloudDataModelGeneralCreditCard
        expect(instance).to.be.a(DkPlusApi.DkCloudDataModelGeneralCreditCard);
      });

      it('should have the property cardType (base name: "CardType")', function() {
        // TODO: update the code to test the property cardType
        expect(instance).to.have.property('cardType');
        // expect(instance.cardType).to.be(expectedValueLiteral);
      });

      it('should have the property cardNumber (base name: "CardNumber")', function() {
        // TODO: update the code to test the property cardNumber
        expect(instance).to.have.property('cardNumber');
        // expect(instance.cardNumber).to.be(expectedValueLiteral);
      });

      it('should have the property expDate (base name: "ExpDate")', function() {
        // TODO: update the code to test the property expDate
        expect(instance).to.have.property('expDate');
        // expect(instance.expDate).to.be(expectedValueLiteral);
      });

      it('should have the property sSNumber (base name: "SSNumber")', function() {
        // TODO: update the code to test the property sSNumber
        expect(instance).to.have.property('sSNumber');
        // expect(instance.sSNumber).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "Name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

    });
  });

}));
