/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkPlusAPIModelsInvoicePaymentPlanCreate', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkPlusAPIModelsInvoicePaymentPlanCreate();
      });

      it('should create an instance of DkPlusAPIModelsInvoicePaymentPlanCreate', function() {
        // TODO: update the code to test DkPlusAPIModelsInvoicePaymentPlanCreate
        expect(instance).to.be.a(DkPlusApi.DkPlusAPIModelsInvoicePaymentPlanCreate);
      });

      it('should have the property description (base name: "Description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "Amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property netAmount (base name: "NetAmount")', function() {
        // TODO: update the code to test the property netAmount
        expect(instance).to.have.property('netAmount');
        // expect(instance.netAmount).to.be(expectedValueLiteral);
      });

      it('should have the property transactions (base name: "Transactions")', function() {
        // TODO: update the code to test the property transactions
        expect(instance).to.have.property('transactions');
        // expect(instance.transactions).to.be(expectedValueLiteral);
      });

      it('should have the property reference (base name: "Reference")', function() {
        // TODO: update the code to test the property reference
        expect(instance).to.have.property('reference');
        // expect(instance.reference).to.be(expectedValueLiteral);
      });

      it('should have the property card (base name: "Card")', function() {
        // TODO: update the code to test the property card
        expect(instance).to.have.property('card');
        // expect(instance.card).to.be(expectedValueLiteral);
      });

      it('should have the property senderId (base name: "SenderId")', function() {
        // TODO: update the code to test the property senderId
        expect(instance).to.have.property('senderId');
        // expect(instance.senderId).to.be(expectedValueLiteral);
      });

    });
  });

}));
