/*
 * dkPlus API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DkPlusApi);
  }
}(this, function(expect, DkPlusApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DkPlusAPIModelsGeneralLedgerOptions', function() {
      beforeEach(function() {
        instance = new DkPlusApi.DkPlusAPIModelsGeneralLedgerOptions();
      });

      it('should create an instance of DkPlusAPIModelsGeneralLedgerOptions', function() {
        // TODO: update the code to test DkPlusAPIModelsGeneralLedgerOptions
        expect(instance).to.be.a(DkPlusApi.DkPlusAPIModelsGeneralLedgerOptions);
      });

      it('should have the property post (base name: "Post")', function() {
        // TODO: update the code to test the property post
        expect(instance).to.have.property('post');
        // expect(instance.post).to.be(expectedValueLiteral);
      });

      it('should have the property generateVoucher (base name: "GenerateVoucher")', function() {
        // TODO: update the code to test the property generateVoucher
        expect(instance).to.have.property('generateVoucher');
        // expect(instance.generateVoucher).to.be(expectedValueLiteral);
      });

    });
  });

}));
